apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
  labels:
    app: weather-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
      - name: weather
        image: ghcr.io/kojotpg/weather-station:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: thermal
          mountPath: /sys/class/thermal
          readOnly: true
      volumes:
      - name: thermal
        hostPath:
          path: /sys/class/thermal
---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-service
spec:
  selector:
    app: weather-station
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: weather-station-ingress
spec:
  entryPoints: [web]
  routes:
  - match: PathPrefix(`/weather`)
    kind: Rule
    services:
    - name: weather-station-service
      port: 80
    middlewares:
    - name: weather-stripprefix
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: weather-stripprefix
spec:
  stripPrefix:
    prefixes: [/weather]